#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

git lfs install && git lfs pull

# Download, check integrity, uncompress and patch the source from GitHub
ynh_hide_warnings git clone https://iceshrimp.dev/iceshrimp/iceshrimp.git "$install_dir" --quiet

chmod 750 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

# Configure redis
redis_db=$(ynh_redis_get_free_db)
ynh_app_setting_set --key=redis_db --value="$redis_db"

ynh_config_add --template="default.yml" --destination="$install_dir/.config/default.yml"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

ynh_config_add_logrotate

yunohost service add $app --description="A interplanetary blogging platform" --log="/var/log/$app/$app.log"

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building app... This will take some time."

pushd "$install_dir"
	corepack enable
    ynh_hide_warnings corepack prepare yarn@latest --activate
	ynh_hide_warnings ynh_exec_as_app yarn install
	ynh_hide_warnings ynh_exec_as_app NODE_ENV=production yarn build
	ynh_hide_warnings ynh_exec_as_app yarn run init
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service=$app --action="start" --log_path=systemd --wait_until="All workers started"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
