#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies... This might take some time."

ynh_nodejs_install

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

mkdir -p "$install_dir"
chown -R $app:www-data "$install_dir"

git lfs install && git lfs pull

ynh_hide_warnings git clone https://iceshrimp.dev/iceshrimp/iceshrimp.git "$install_dir" --quiet

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

# Configure redis
redis_db=$(ynh_redis_get_free_db)
ynh_app_setting_set --key=redis_db --value="$redis_db"

ynh_config_add --template="default.yml" --destination="$install_dir/.config/default.yml"

chmod 400 "$install_dir/.config/default.yml"
chown $app:$app "$install_dir/.config/default.yml"

chmod 750 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building app... This will take some time."

pushd "$install_dir"
	ynh_exec_as_app corepack enable
	ynh_exec_as_app corepack prepare --activate
	ynh_hide_warnings ynh_exec_as_app yarn
	ynh_hide_warnings ynh_exec_as_app NODE_ENV=production yarn build
	ynh_hide_warnings ynh_exec_as_app yarn run init
popd

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression "Configuring $app's systemd service..."

ynh_config_add_nginx

ynh_config_add_systemd

ynh_config_add_logrotate

yunohost service add $app --description="A interplanetary blogging platform" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start" --log_path=systemd --wait_until="All workers started"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
